# fly.toml app configuration file generated for phonebook-be-damp-dew-6539 on 2025-02-26T15:11:22+07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'phonebook-be-damp-dew-6539'
primary_region = 'sin'

[env]
PORT="3001"

[build]

[http_service]
  internal_port = 3001
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[[vm]]
  memory = '1gb'
  cpu_kind = 'shared'
  cpus = 1
